
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VALKI
 */
public class SEARCH_PD extends javax.swing.JFrame {
Statement stare;
Connection con=null;
    /**
     * Creates new form Cautare
     */
    public SEARCH_PD() {
        initComponents();
        con=CONNECT.conect();
          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cautare = new javax.swing.JButton();
        Revenire = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tnume = new javax.swing.JTextField();
        lista = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        tnume2 = new javax.swing.JTextField();
        cautare1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cautare.setBackground(new java.awt.Color(0, 153, 153));
        cautare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare.setText("SEARCH");
        cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareActionPerformed(evt);
            }
        });

        Revenire.setBackground(new java.awt.Color(0, 153, 153));
        Revenire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Revenire.setText("CLOSE");
        Revenire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenireActionPerformed(evt);
            }
        });

        jLabel1.setText("ENTER THE FULL NAME OF THE MEDICATION:");

        jLabel2.setText("ENTER PART OF THE NAME OF THE MEDICATION:");

        tnume2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnume2ActionPerformed(evt);
            }
        });

        cautare1.setBackground(new java.awt.Color(0, 153, 153));
        cautare1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare1.setText("SEARCH");
        cautare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautare1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("SEARCH RECORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Revenire))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnume2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cautare1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(tnume, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tnume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cautare1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tnume2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Revenire)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautareActionPerformed
lista.removeAll();
        String numeinterfata=tnume.getText();
        try {
            stare =con.createStatement();
           String intrebare ="SELECT * FROM `medicamente` where `Nume`='"+numeinterfata+"'";
            
           ResultSet rezultat = stare.executeQuery(intrebare);
           int j=0;
           while(rezultat.next()) 
           {
                String nume = rezultat.getString("nume");
                String datae = rezultat.getString("Datae");
                double pret=rezultat.getDouble("Pret");
                
                String s = "";
                s+=nume+" EXPIRATION DATE " +datae +" ,PRICE  "+ pret ;
                lista.add(s);
                j++;
            }
            if(j==0) 
            JOptionPane.showMessageDialog(rootPane, "RECORD NOT FOUND");
           
            
            
        }  catch(SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }
    }//GEN-LAST:event_cautareActionPerformed

    private void RevenireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenireActionPerformed

        setVisible(false);
    }//GEN-LAST:event_RevenireActionPerformed

    private void cautare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautare1ActionPerformed
    lista.removeAll();
        String numeinterfata=tnume2.getText();
        try {
            stare =con.createStatement();
           String intrebare ="SELECT * FROM `medicamente` where `Nume` LIKE '%"+ numeinterfata+"%'";
            
           ResultSet rezultat = stare.executeQuery(intrebare);
           int j=0;
           while(rezultat.next()) 
           {
            String nume = rezultat.getString("nume");
                String datae = rezultat.getString("Datae");
                double pret=rezultat.getDouble("Pret");
                
                String s = "";
                s+=nume+" EXPIRATION DATE  " +datae +" ,PRICE  "+ pret ;
                lista.add(s);
                j++;
            }
            if(j==0) 
            JOptionPane.showMessageDialog(rootPane, "RECORD NOT FOUND");
           
            
            
        }  catch(SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_cautare1ActionPerformed

    private void tnume2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnume2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnume2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCH_PD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Revenire;
    private javax.swing.JButton cautare;
    private javax.swing.JButton cautare1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.List lista;
    private javax.swing.JTextField tnume;
    private javax.swing.JTextField tnume2;
    // End of variables declaration//GEN-END:variables
}
